export { DownloadSection } from './DownloadSection'
export { Features } from './Features'
export { Hero } from './Hero'
export { LastNews } from './LastNews'
export { Testimonial } from './Testimonial'
